/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PatientDTO } from '../model/models';
import { PatientVO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PatientControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param patientVO 
     */
    createPatient(patientVO: PatientVO, extraHttpRequestParams?: any): Observable<PatientDTO>;

    /**
     * 
     * 
     * @param id 
     */
    getPatientById(id: string, extraHttpRequestParams?: any): Observable<PatientDTO>;

}
